/**
 * Placeholder English deck. Card ids are derived from position, so append new
 * cards rather than inserting them if you care about ids staying stable.
 */

export const EN_PROMPTS = [
  { text: 'The secret to a happy life is ___.', pick: 1 },
  { text: 'I never leave the house without ___.', pick: 1 },
  { text: 'My therapist says my real problem is ___.', pick: 1 },
  { text: 'What ruined the office party? ___', pick: 1 },
  { text: 'Nothing says romance like ___.', pick: 1 },
  { text: 'The new national holiday celebrates ___.', pick: 1 },
  { text: 'First I take ___, then I take ___.', pick: 2 },
  { text: 'My autobiography will be called ___.', pick: 1 },
  { text: 'The worst thing to find in your soup is ___.', pick: 1 },
  { text: 'Step one: ___. Step two: ___. Step three: profit.', pick: 2 },
  { text: 'I got fired for ___.', pick: 1 },
  { text: 'What is the sound of one hand clapping? ___', pick: 1 },
  { text: '___ is the reason I have trust issues.', pick: 1 },
  { text: "The zoo's newest exhibit is ___.", pick: 1 },
  { text: 'In my defence, ___ seemed like a good idea at the time.', pick: 1 },
  { text: 'What did I bring back from holiday? ___', pick: 1 },
  { text: 'This meeting could have been an email about ___.', pick: 1 },
  { text: '___: now available in travel size.', pick: 1 },
  { text: 'My grandmother left me ___ in her will.', pick: 1 },
  { text: 'The apocalypse will begin with ___.', pick: 1 },
  { text: 'What keeps me up at night? ___', pick: 1 },
  { text: 'Do not operate heavy machinery after ___.', pick: 1 },
  { text: 'The password hint is ___.', pick: 1 },
  { text: 'I lost my job, my flat and ___.', pick: 1 },
  { text: 'Every family has one: ___.', pick: 1 },
  { text: 'The recipe calls for ___ and a lot of patience.', pick: 1 },
  { text: '___ walks into a bar. The bartender says ___.', pick: 2 },
  { text: "This year's most requested wedding song is ___.", pick: 1 },
  { text: 'Scientists have finally proven that ___ causes ___.', pick: 2 },
  { text: 'The tourist brochure promised ___.', pick: 1 },
] as const;

export const EN_ANSWERS = [
  'a slightly damp handshake',
  "my ex's playlist",
  'unpaid internships',
  'a pigeon with a plan',
  'the smell of a new laptop',
  'aggressive small talk',
  'a group project',
  'Monday',
  'my search history',
  'an inflatable castle',
  'the last slice of pizza',
  'emotional support hummus',
  'a very confident toddler',
  'expired coupons',
  'the office printer',
  'three raccoons in a trenchcoat',
  'a motivational poster',
  'silent judgement',
  'gym membership guilt',
  'a haunted air fryer',
  "my browser's forty-seven open tabs",
  'the family group chat',
  'a suspiciously cheap flight',
  'leftover birthday cake',
  "someone else's alarm going off",
  'a passive-aggressive sticky note',
  'unsolicited advice',
  'a dead houseplant',
  'questionable life choices',
  "the neighbour's cat",
  'a spreadsheet nobody asked for',
  'cold coffee',
  'an unnecessary apology',
  "my parents' opinion",
  'a mystery bruise',
  'the tenth season of anything',
  'a hotel breakfast buffet',
  'wet socks',
  'a very long voicemail',
  'the fine print',
  'airport wifi',
  'a lukewarm bath',
  'my imaginary competence',
  'the last bus home',
  'a haircut I did not ask for',
  'elevator silence',
  'an aggressively healthy smoothie',
  'the wrong meeting link',
  'a chair that squeaks',
  'unread terms and conditions',
  'second breakfast',
  'a slightly illegal shortcut',
  'the sound of a fax machine',
  "my future self's problem",
  'an extremely enthusiastic salesman',
  'a plastic fork',
  'the wifi password on a napkin',
  'a nap that lasted four hours',
  "someone else's umbrella",
  'a very serious duck',
] as const;
