/**
 * Turkish deck. Card ids are derived from position, so append new cards rather
 * than inserting them if you care about ids staying stable.
 */

export const TR_PROMPTS = [
  { text: '___ yüzünden kovuldum.', pick: 1 },
  { text: 'Aile yemeğinde asla ___ hakkında konuşma.', pick: 1 },
  { text: "Türkiye'de hiçbir şey ___ kadar hızlı bitmedi.", pick: 1 },
  { text: 'Bana göre huzur ___.', pick: 1 },
  { text: 'Sabah uyandığımda ilk aklıma gelen: ___.', pick: 1 },
  { text: '___ olmadan bu ülkede yaşanmaz.', pick: 1 },
  { text: 'Hayatımın en büyük pişmanlığı: ___.', pick: 1 },
  { text: 'Doktora asıl söylemem gereken şey ___.', pick: 1 },
  { text: 'Yeni yıl kararım: daha az ___.', pick: 1 },
  { text: '___ bir insanı olduğundan yaşlı gösterir.', pick: 1 },
  { text: 'Bu evde tartışma çıkarmak istiyorsan ___ demen yeter.', pick: 1 },
  { text: "CV'me yazamadığım en büyük yeteneğim: ___.", pick: 1 },
  { text: 'Annem bana hâlâ ___ konusunda güvenmiyor.', pick: 1 },
  { text: 'Bu ülkede herkesin ortak derdi: ___.', pick: 1 },
  { text: 'Ben gençken ___ vardı, şimdi ___ var.', pick: 2 },
  { text: 'Terapide konuşmaktan kaçındığım konu: ___.', pick: 1 },
  { text: '___ beni her seferinde hayal kırıklığına uğratıyor.', pick: 1 },
  { text: 'Arkadaşlığın gerçek testi ___.', pick: 1 },
  { text: 'Patronum ___ olduğunu öğrenirse işim biter.', pick: 1 },
  { text: 'Mezuniyet konuşmamda ___ demek isterdim.', pick: 1 },
  { text: 'Bu şehirde yaşamanın bedeli: ___.', pick: 1 },
  { text: 'En son ___ yüzünden ağladım.', pick: 1 },
  { text: 'Kimse itiraf etmiyor ama hepimiz ___ seviyoruz.', pick: 1 },
  { text: 'İlk buluşmada asla ___ getirme.', pick: 1 },
  { text: 'Hayatım ___ ile ___ arasında geçiyor.', pick: 2 },
  { text: 'Ölmeden önce bir kez ___ denemek istiyorum.', pick: 1 },
  { text: 'Bu evde kimse ___ konusunu açmıyor.', pick: 1 },
  { text: 'En büyük korkum ___.', pick: 1 },
  { text: 'Türk misafirperverliği demek ___ demek.', pick: 1 },
  { text: 'Sınavdan önceki gece aklımdan geçen: ___.', pick: 1 },
  { text: '___ olmasa bu iş çoktan biterdi.', pick: 1 },
  { text: 'Beni benden alan şey: ___.', pick: 1 },
  { text: 'Herkesin telefonunda sakladığı şey: ___.', pick: 1 },
  { text: 'Bayram ziyaretinin özeti: ___.', pick: 1 },
  { text: '___ gördüğüm anda karşı kaldırıma geçerim.', pick: 1 },
  { text: 'Bu ilişkiyi bitiren şey ___ oldu.', pick: 1 },
  { text: 'Hayatta öğrendiğim en pahalı ders: ___.', pick: 1 },
  { text: 'Yeni tanıştığım insanlara ___ olduğumu söylüyorum.', pick: 1 },
  { text: 'Gece üçte aklıma gelen şey: ___.', pick: 1 },
  { text: '___ ile ___ aynı cümlede geçmemeli.', pick: 2 },
] as const;

export const TR_ANSWERS = [
  // Aile
  'aile WhatsApp grubu',
  'bayram harçlığı',
  'halamın "ne zaman evleniyorsun" sorusu',
  'annemin dolabındaki poşet dolu poşet',
  'misafir odasındaki oturulmayan koltuk',
  'babamın "ben senin yaşındayken" girişi',
  'yılbaşı çekilişinden çıkan tencere seti',
  'kuzenimin düğün fotoğrafları',
  'yatak altındaki valizler',
  'dedemin radyosu',
  'balkondaki turşu kavanozları',
  '"biz size gelelim" telefonu',
  'annemin sakladığı bebeklik fotoğraflarım',
  'asla açılmayan misafir çayı takımı',
  'ailenin en başarılı çocuğu',
  'babamın araba çizikleri',
  'aynı hikâyenin dördüncü kez anlatılması',
  'kimsenin oturmadığı salon',
  'buzdolabındaki isimsiz kap',
  'teyzemin kolonyası',
  'bayram sabahı el öpme sırası',
  'aile büyüğünün siyasi yorumu',
  'yemekte tabağıma konan üçüncü porsiyon',
  'annemin arkadaşının kızı',
  'eve gelen kargoyu saklama refleksi',

  // İş
  'toplantıya dönüşen e-posta',
  '"kısa bir dakikanı alabilir miyim"',
  'ofis yazıcısı',
  'mutfaktaki isimsiz yoğurt',
  'patronun espri yaptığı an',
  'zam görüşmesi',
  'yıllık izin talebi formu',
  'çalışmayan klima',
  'zorunlu şirket etkinliği',
  `LinkedIn'deki "heyecanla duyuruyorum" gönderisi`,
  'toplantıdan sonraki toplantı',
  'mesai bitimine üç dakika kala gelen mesaj',
  'şirket telefonundan gelen aramalar',
  'açık ofis',
  'birinin kulaklıksız izlediği video',
  'kimsenin okumadığı prosedür dokümanı',
  "CV'mdeki üç yıllık boşluk",
  "İK'nın motivasyon maili",
  'mola odasındaki bozuk kahve makinesi',
  '"acil" etiketli talep',
  'performans değerlendirmesi',
  'yeni gelen stajyerin özgüveni',
  'bir türlü onaylanmayan masraf fişi',
  'pazartesi sabahı toplantısı',
  'şirket bilgisayarındaki yasaklı siteler',

  // Market
  'kasadaki bozukluk arayışı',
  'son kullanma tarihi bugün olan indirim reyonu',
  'alışveriş listesinde olmayan on ürün',
  'kendi kendine ödeme kasasının "beklenmeyen ürün" uyarısı',
  'park yerindeki başıboş market arabası',
  'manavdaki "elleme" uyarısı',
  'kasiyerin sorduğu market kartı',
  'reyon arasında telefonla danışma',
  'poşet ücreti',
  'tartıda çıkmayan barkod',
  'en arkadaki tarihi kontrol etme refleksi',
  'kasadaki tek açık sıra',
  'sepetteki ezilen ekmek',
  '"bu kampanya kapsamında değil"',
  'dondurucu reyonunun soğuğu',
  'üç al iki öde tuzağı',
  'fiyatı rafla uyuşmayan ürün',
  'alışverişten sonra unutulan tek şey',
  'market müziği',
  'numune dağıtan görevli',
  'kasada arkadan gelen baskı',
  'her seferinde alınan gereksiz sos',
  'aynı yoğurdun beş çeşidi',
  'kredi kartı taksit sorusu',
  'park çıkışında kaybolan fiş',

  // Düğün
  'takı takma töreni',
  'gelin arabası konvoyu',
  'davetli listesindeki tanımadığım isimler',
  'salon menüsündeki mercimek çorbası',
  'halay sırasında düşen telefon',
  '"sıra sende" bakışları',
  'profesyonel fotoğrafçının poz talimatları',
  'gelinin arkadaş grubu',
  'damadın havaya atılması',
  'nikâh şahidi seçimi',
  'düğün davetiyesinin gelme şekli',
  'masaya oturma krizi',
  'takı takarken çekilen video',
  'gece yarısı servis edilen börek',
  'uzaktan akraba tebrikleri',
  'salonun ses sistemi',
  'pastanın plastik katları',
  'gelinliğin eteğini taşıyan çocuk',
  'düğün sonrası hesap konuşmaları',
  'kına gecesindeki ağlama sahnesi',
  'dansı bilmeyen damat',
  'davetiyede yazan "saat 19.00"',
  'masadaki kolonya',
  'fotoğraf sırasında bekleyen kuyruk',
  'düğün hediyesi olarak verilen çeyrek',

  // Banka
  'sıra numarası fişi',
  '"bir de şu formu doldurun"',
  'kredi başvurusu reddi',
  "ATM'nin yuttuğu kart",
  'şubede geçen kırk beş dakika',
  'hesap işletim ücreti',
  'müşteri temsilcisinin sattığı sigorta',
  'internet bankacılığı şifresi sıfırlama',
  'kredi kartı ekstresi',
  'limit artırma teklifi araması',
  'sabah dokuzda açılmayan şube',
  'imza örneğinin tutmaması',
  'otomatik ödeme talimatı',
  '"sisteme düştü, bekleyin"',
  'nakit çekim komisyonu',
  'şube müdürüne yönlendirilme',
  'onaylanmayan havale',
  'vadeli hesabın faizi',
  'aidat borcu bildirimi',
  'üç günlük valör',
  'kefil arayışı',
  'kimlik fotokopisi talebi',
  'bankamatikteki uzun kuyruk',
  'SMS onay kodunun gelmemesi',
  'hesap özetindeki tanımadığım harcama',

  // İnternet
  'kesilen bağlantı',
  'modemi kapatıp açma ritüeli',
  '"beni hatırla" işaretlemesine rağmen çıkış yapılması',
  'çerez onayı penceresi',
  'unutulan şifre',
  'iki faktörlü doğrulamanın gelmeyen kodu',
  'abonelik iptali için gizlenen buton',
  'otomatik oynatılan video',
  'sonsuz kaydırma',
  'okunmamış bildirim sayısı',
  'yorumlardaki tartışma',
  'profil fotoğrafı seçimi',
  'eski gönderilerimin hatırlatılması',
  '"bu içeriği beğenmiyorum" seçeneği',
  'yükleme çubuğunun yüzde doksan dokuzda durması',
  'reklam engelleyici uyarısı',
  'sesli mesaj',
  'gruptan sessize alınma',
  'yanlış kişiye giden mesaj',
  'sildiğim mesajın "bu mesaj silindi" izi',
  'arama geçmişim',
  'üç saatlik "beş dakikalık" video',
  'kaydedilenler klasörü',
  'takip ettiğim ama tanımadığım hesaplar',
  'internet paketinin bitmesi',

  // Eski sevgili
  'engellenmiş numara',
  'ortak arkadaş grubu',
  'silinmeyen fotoğraflar',
  'evde kalan diş fırçası',
  'doğum gününün hatırlatılması',
  '"arkadaş kalalım" cümlesi',
  'sosyal medyada gizli takip',
  'geri istenen kitap',
  'ortak dinlenen şarkı',
  'son mesajın okunup cevaplanmaması',
  'yıldönümü bildirimi',
  'yeni sevgilisinin profili',
  'geceleri gelen mesaj',
  'kaydedilmiş adres',
  'birlikte gidilen kafe',
  'ailesinin hâlâ arkadaş listemde olması',
  'birlikte alınan bitki',
  '"yanlışlıkla" gönderilen mesaj',
  'ayrılık gerekçesinin üçüncü versiyonu',
  'unutulan şarj aleti',
  'aynı arkadaş grubundaki karşılaşma',
  'geri verilen anahtar',
  'telefondaki kayıt ismi',
  'çok konuşulmuş bir kavga',
  'numarasını ezbere bilmek',

  // Üniversite
  'bütünleme sınavı',
  'grup ödevinde çalışmayan üçüncü kişi',
  'kantindeki tost kuyruğu',
  'vize haftası uyku düzeni',
  'devamsızlık sınırı',
  'hoca dinlerken açık kalan laptop',
  'kütüphanedeki yer kapma',
  'öğrenci evindeki bulaşık',
  'slaytları paylaşmayan sınıf arkadaşı',
  'sabah dokuz dersi',
  'ders seçme sisteminin çökmesi',
  '"bu sınavda çıkmaz" denen soru',
  'not ortalaması hesaplama',
  'kredi kartı taksitine bölünen yurt parası',
  'dönem projesinin son gecesi',
  'yoklama kâğıdına atılan sahte imza',
  'asistanın tavrı',
  'staj defteri',
  'mezuniyet töreni provası',
  'burs başvurusu',
  'sınavdan çıkınca yapılan cevap karşılaştırması',
  'fotokopiciden alınan ders notları',
  'ilk dersin ilk yirmi dakikası',
  'dönem sonu ortalama krizi',
  'diploma töreninde okunmayan isim',

  // Askerlik
  'nöbet çizelgesi',
  'yoklama sırası',
  'sabah içtiması',
  'komutanın ruh hali',
  'postalın ayağa uymayan numarası',
  'izin belgesi',
  'yemekhane sırası',
  'kantin borcu',
  'ranza düzeni',
  'terhis sayacı',
  'fotoğraf çekilme yasağı',
  'tuvalet temizliği görevi',
  '"yat kalk" cezası',
  'nöbette uyuklama',
  'aile ziyareti günü',
  'matara suyu',
  'eğitim sahasındaki toz',
  'telefonun teslim edilmesi',
  'gece nöbeti soğuğu',
  'bölük onbaşısı',
  'kısa dönem tartışması',
  'postaneye giden mektup',
  'ayakkabı boyama saati',
  'içtimada söylenen marş',
  'terhis günü sayma alışkanlığı',

  // Apartman
  'aidat toplayan yönetici',
  'asansörün bozulması',
  'üst kattaki ayak sesleri',
  'çamaşır ipindeki komşu çamaşırı',
  'kapıcıya verilen bahşiş',
  'apartman toplantısı',
  'merdivende bırakılan ayakkabılar',
  'çöp poşetinin kapıda unutulması',
  'otopark yeri kavgası',
  'balkondan sarkan halı',
  'apartman WhatsApp grubu',
  'gece yarısı matkap sesi',
  'asansördeki sessizlik',
  'su faturasının ortak paylaşımı',
  'giriş kapısının açık kalması',
  'komşunun kedisi',
  'kapı önüne bırakılan kargo',
  'yönetim planındaki madde',
  'doğalgaz kombisi arızası',
  'üst kattaki tadilat',
  'apartman girişindeki koku',
  'aidat borcu listesi',
  'zilin yanlış daireye basılması',
  'sokakta park eden yabancı araba',
  'kapıcının izin günü',

  // Hastane
  'randevu saatinden iki saat sonra girilen muayene',
  'e-Nabız şifresi',
  'sevk zinciri',
  'acildeki triyaj sırası',
  '"başka şikâyetiniz var mı"',
  'tahlil sonucunu beklemek',
  'reçetedeki okunmayan yazı',
  'hastane koridorundaki sıra',
  'muayene sırasında telefonu çalan doktor',
  'refakatçi koltuğu',
  'kan alma odasındaki bakış',
  'katılım payı',
  'ilacın yan etki listesi',
  'sağlık ocağındaki tek doktor',
  'MR randevusunun üç ay sonrasına verilmesi',
  'hastane yemeği',
  'check-up paketi',
  'sıra numarasının atlanması',
  'doktorun bilgisayara bakması',
  'aile hekimi değişikliği',
  'ateş ölçme kuyruğu',
  'röntgen odasının kapısı',
  'reçetesiz istenen ilaç',
  'hastanedeki otopark ücreti',
  'taburcu evrakları',
] as const;
