/**
 * Placeholder Turkish deck. Card ids are derived from position, so append new
 * cards rather than inserting them if you care about ids staying stable.
 */

export const TR_PROMPTS = [
  { text: 'Mutlu bir hayatın sırrı ___.', pick: 1 },
  { text: 'Evden çıkarken asla ___ unutmam.', pick: 1 },
  { text: 'Terapistim asıl sorunumun ___ olduğunu söylüyor.', pick: 1 },
  { text: 'Şirket yemeğini ne mahvetti? ___', pick: 1 },
  { text: 'Romantizm dediğin ___ demek.', pick: 1 },
  { text: 'Yeni resmi tatilimiz ___ için.', pick: 1 },
  { text: 'Önce ___ alırım, sonra ___.', pick: 2 },
  { text: 'Otobiyografimin adı ___ olacak.', pick: 1 },
  { text: 'Çorbanın içinden çıkabilecek en kötü şey ___.', pick: 1 },
  { text: 'Birinci adım: ___. İkinci adım: ___. Üçüncü adım: köşeyi dön.', pick: 2 },
  { text: '___ yüzünden kovuldum.', pick: 1 },
  { text: 'Tek elin nesi var? ___', pick: 1 },
  { text: 'Güven sorunlarımın sebebi ___.', pick: 1 },
  { text: 'Hayvanat bahçesinin yeni gözdesi ___.', pick: 1 },
  { text: 'Savunmamda söyleyeyim, ___ o an iyi bir fikir gibi görünmüştü.', pick: 1 },
  { text: 'Tatilden ne getirdim dersiniz? ___', pick: 1 },
  { text: 'Bu toplantı aslında ___ hakkında bir e-posta olabilirdi.', pick: 1 },
  { text: '___: artık seyahat boyunda.', pick: 1 },
  { text: 'Babaannem bana vasiyetinde ___ bıraktı.', pick: 1 },
  { text: 'Kıyamet ___ ile başlayacak.', pick: 1 },
  { text: 'Gece gözümü açık tutan şey ___.', pick: 1 },
  { text: '___ sonrası ağır makine kullanmayınız.', pick: 1 },
  { text: 'Şifre ipucu: ___', pick: 1 },
  { text: 'İşimi, evimi ve ___ kaybettim.', pick: 1 },
  { text: 'Her ailede bir tane vardır: ___', pick: 1 },
  { text: 'Tarif ___ ve bolca sabır istiyor.', pick: 1 },
  { text: '___ bara girer. Barmen der ki ___.', pick: 2 },
  { text: 'Bu yılın en çok istenen düğün şarkısı ___.', pick: 1 },
  { text: 'Bilim insanları nihayet ___ yüzünden ___ olduğunu kanıtladı.', pick: 2 },
  { text: 'Turizm broşüründe ___ vaat ediliyordu.', pick: 1 },
] as const;

export const TR_ANSWERS = [
  'hafif nemli bir tokalaşma',
  'eski sevgilimin çalma listesi',
  'maaşsız stajlar',
  'planı olan bir güvercin',
  'yeni laptop kokusu',
  'agresif hoşbeş',
  'grup ödevi',
  'pazartesi',
  'arama geçmişim',
  'şişme kale',
  'son dilim pizza',
  'duygusal destek humusu',
  'kendinden fazla emin bir çocuk',
  'süresi geçmiş indirim kuponları',
  'ofis yazıcısı',
  'trençkot giymiş üç rakun',
  'motivasyon posteri',
  'sessiz yargılama',
  'spor salonu suçluluğu',
  'perili bir airfryer',
  'tarayıcımdaki kırk yedi sekme',
  'aile grubu',
  'şüpheli derecede ucuz bir bilet',
  'dünden kalan yaş pasta',
  'başkasının alarm sesi',
  'iğneleyici bir post-it',
  'istenmeyen tavsiye',
  'ölmüş bir saksı çiçeği',
  'tartışmalı hayat kararları',
  'komşunun kedisi',
  'kimsenin istemediği bir tablo',
  'soğumuş kahve',
  'gereksiz bir özür',
  'annemin fikri',
  'nereden çıktığı belirsiz bir morluk',
  'her şeyin onuncu sezonu',
  'otel açık büfesi',
  'ıslak çorap',
  'çok uzun bir sesli mesaj',
  'sözleşmenin küçük yazıları',
  'havalimanı wifisi',
  'ılık bir banyo',
  'hayali yeterliliğim',
  'son otobüs',
  'istemediğim bir saç kesimi',
  'asansördeki sessizlik',
  'aşırı sağlıklı bir smoothie',
  'yanlış toplantı linki',
  'gıcırdayan bir sandalye',
  'okunmamış kullanım koşulları',
  'ikinci kahvaltı',
  'hafif yasa dışı bir kestirme',
  'faks makinesi sesi',
  'gelecekteki halimin sorunu',
  'aşırı hevesli bir satıcı',
  'plastik çatal',
  'peçeteye yazılmış wifi şifresi',
  'dört saat süren bir şekerleme',
  'başkasının şemsiyesi',
  'çok ciddi bir ördek',
] as const;
